Vendas_Site/Areas/Admin/Controllers/AdminImagensController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Vendas_Site.Models;

namespace Vendas_Site.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminImagensController : Controller
    {
        private readonly ConfigurationImagens _myconfig;
        private readonly IWebHostEnvironment _webHost;

        public AdminImagensController(IWebHostEnvironment hostingEnvironment,
           IOptions<ConfigurationImagens> myConfiguration)
        {
            _webHost = hostingEnvironment;
            _myconfig = myConfiguration.Value;
        }

        public IActionResult Index()
        {
            return View();
        }

         public async Task<IActionResult> UploadFiles(List<IFormFile> files)
        {
            if(files == null || files.Count == 0)
            {
                ViewData["Erro"] = "Arquivo(s) não selecionado(s)";
                return View(ViewData);
            }

            if (files.Count > 10)
            {
                ViewData["Erro"] = "Quantidade excessiva de arquivos não permitida";
                return View(ViewData);
            }

            long size = files.Sum(p => p.Length);

            var filesPathName = new List<string>();
            var filePath = Path.Combine(_webHost.WebRootPath, _myconfig.NomePastaImagensProdutos);

            foreach(var formFile in files)
            {
                if(formFile.FileName.Contains(".jpg") || formFile.FileName.Contains(".png") ||
                     formFile.FileName.Contains(".gif"))
                {
                    var fileNameWithPath = string.Concat(filePath, "\\", formFile.FileName);
                    
                    filesPathName.Add(fileNameWithPath);

                    using var stream = new FileStream(fileNameWithPath, FileMode.Create);
                    await formFile.CopyToAsync(stream);

                }
            }

            ViewData["Resultado"] = $"{filesPathName.Count} foram enviados ao servidor com sucesso!"
                                      + $"Total de :{size} bytes";

            ViewBag.Arquivos = filesPathName;

            return View(ViewData);
        }

        public IActionResult GetImages()
        {
            FileManagerModel model = new();

            var serverImagesPath = Path.Combine(_webHost.WebRootPath, _myconfig.NomePastaImagensProdutos);

            DirectoryInfo directory = new(serverImagesPath);

            FileInfo[] filer = directory.GetFiles();

            model.PatchImagensProduto = _myconfig.NomePastaImagensProdutos;

            if(filer.Length == 0)
            {
                ViewData["Erro"] = $"Não foram encontrados nenhum arquivo em {serverImagesPath}";
            }

            model.Files = filer;

            return View(model);
        }

        public IActionResult DeleteFile(string fileName)
        {
            string imagemDeleta = Path.Combine(_webHost.WebRootPath, _myconfig.NomePastaImagensProdutos + "\\", fileName);

            if (System.IO.File.Exists(imagemDeleta))
            {
                System.IO.File.Delete(imagemDeleta);

                ViewData["Deletado"] = $"O arquivo {fileName} foi deletado com  sucesso";
            }

            return View("Index");
        }
    }
}

Vendas_Site/Areas/Admin/Views/AdminImagens/GetImages.cshtml
@model FileManagerModel
@{
    ViewBag.Title = "Arquivos";
}
@if (Model.Files != null)
{
    <h3>Imagens:</h3>
    <hr />
    var caminho = Model.PatchImagensProduto;
    <div class="row">
        @foreach (FileInfo file in Model.Files)
        {
            <div class="column">
                <img src="~/@caminho/@file.Name" width="125" height="125" title="@file.Name" asp-append-version="true">
                <div style="padding:10px;text-align:left">
                    <a href="@Url.Action("Deletefile","AdminImagens",new { fileName=file.Name})">Deletar</a>
                </div>
            </div>
        }
    </div>
}
@if (ViewData["Erro"] != null)
{
    <img src="~/images/erro1.png" width="150" height="150" />
    <h4>@ViewData["Erro"]</h4>
}
<div class="clearfix"></div>
<hr />
<div>
    <span>Para ver o nome do arquivo passa o mouse na imagem</span>
</div>
<div class="form-group">
    <a class="btn btn-outline-info" asp-controller="AdminImagens" asp-action="Index">Retornar</a>
</div>

Vendas_Site/Areas/Admin/Views/AdminImagens/Index.cshtml
<table width="100%">
    <tr>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImagens" asp-action="UploadFiles">
                <img src="~/images/upload2.png" width="200" height="150" />
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><b>Selecione um ou mais arquivos para enviar :</b></p>
                        <p>(Arquivos com o mesmo nome serão sobrescritos)</p>
                        <input type="file" name="files" multiple class="button btn-outline-primary" />
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Enviar Arquivo(s)" class="button btn-outline-primary" />
                    </div>
                </div>
            </form>
        </td>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImagens" asp-action="GetImages">
                <img src="~/images/visualizar1.jpg" width="200" height="200" />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><strong>Visualizar Imagens na pasta do servidor :</strong></p>
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Visualizar Arquivos no servidor" class="button btn-outline-warning" />
                    </div>
                </div>
            </form>
        </td>
    </tr>
</table>

<div class="container">
    @if (ViewData["Deletado"] != null)
    {
        @ViewData["Deletado"]
    }
</div>

Vendas_Site/Areas/Admin/Views/AdminImagens/UploadFiles.cshtml
@{
    ViewData["Title"] = "UploadFiles";
}
<img src="~/images/upload2.png" width="200" height="150" />
<hr />
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        @if (ViewData["Erro"] != null)
        {
            <img src="~/images/erro1.png" width="150" height="150" />
            <h4>@ViewData["Erro"]</h4>
        }
    </div>
    <div class="container">
        @if (ViewData["Resultado"] != null)
        {
            <h4>@ViewData["Resultado"]</h4>
            <hr />
            @if (ViewBag.Arquivos != null)
            {
                @foreach (string arquivo in ViewBag.Arquivos)
                {
                    
                        @arquivo
                   
                }
            }
        }
    </div>
</div>
<div class="form-group">
    <a class="btn btn-outline-info" asp-controller="AdminImagens" asp-action="GetImagens">Exibir Imagens</a>
</div>